Web/ViewModels/TeacherViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Web.Models;

namespace Web.ViewModels
{
    public class TeacherViewModel
    {
        public long Id { get; set; }
        [Required(ErrorMessage = "Please Enter Full Name."), Display(Name = "Full Name")]
        public string FullName { get; set; }
        public Sex Sex { get; set; }
        public int Age { get; set; }
        [Display(Name = "Birth Date")]
        public DateTime BirthDate { get; set; }
        [Display(Name = "Birth Place")]
        public string BirthPlace { get; set; }
    }
}

Web/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.DAL;
using Web.Models;
using Web.ViewModels;

namespace Web.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ApplicationDbContext context = new ApplicationDbContext();
        public List<TeacherViewModel> Teachers { get; set; }

        // GET: Teacher
        public ActionResult Index()
        {
            var teachers = context.Teachers.ToList();
            var teacherViewModels = new List<TeacherViewModel>();
            foreach (var teacher in teachers)
            {
                var teacherViewModel = new TeacherViewModel()
                {
                    Id = teacher.Id,
                    FullName = teacher.FullName,
                    Sex = teacher.Sex,
                    Age = teacher.Age,
                    BirthDate = teacher.BirthDate,
                    BirthPlace = teacher.BirthPlace
                };
                teacherViewModels.Add(teacherViewModel);
            }
            Teachers = teacherViewModels;
            return View(Teachers);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreatePost(TeacherViewModel teacherViewModel)
        {
            var teacher = new Teacher()
            {
                FullName = teacherViewModel.FullName,
                Sex = teacherViewModel.Sex,
                Age = teacherViewModel.Age,
                BirthDate = teacherViewModel.BirthDate,
                BirthPlace = teacherViewModel.BirthPlace
            };
            context.Teachers.Add(teacher);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Web/Views/Teacher/Create.cshtml
@model Web.ViewModels.TeacherViewModel
@{
    ViewBag.Title = "Create Teacher";
}

<h2>Create Teacher</h2>
@using (Html.BeginForm("CreatePost", "Teacher", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="mb-3">
        @Html.LabelFor(model => model.FullName, new { @class = "form-label" })
        @Html.TextBoxFor(model => model.FullName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
    </div>
    <div class="mb-3">
        @Html.LabelFor(model => model.Sex, new { @class = "form-label" })
        @Html.DropDownListFor(model => model.Sex, new SelectList(Enum.GetValues(typeof(Web.Models.Sex))), "- Select Gender -", new { @class = "form-control" })
    </div>
    <div class="mb-3">
        @Html.LabelFor(model => model.Age, new { @class = "form-label" })
        @Html.TextBoxFor(model => model.Age, new { type = "number", @class = "form-control" })
    </div>
    <div class="mb-3">
        @Html.LabelFor(model => model.BirthDate, new { @class = "form-label" })
        @Html.TextBoxFor(model => model.BirthDate, new { type = "date", @class = "form-control" })
    </div>
    <div class="mb-3">
        @Html.LabelFor(model => model.BirthPlace, new { @class = "form-label" })
        @Html.TextBoxFor(model => model.BirthPlace, new { @class = "form-control" })
    </div>
    <button class="btn btn-secondary">Submit</button>
}

Web/Views/Teacher/Index.cshtml
@model List<Web.ViewModels.TeacherViewModel>
@{
    ViewBag.Title = "Teacher";
}

<h2>Teacher</h2>
@Html.ActionLink("+ Create", "Create", "Teacher", new { @class = "btn btn-success" })
@foreach (var teacher in Model)
{
    <p>@teacher.FullName</p>
}